### ISSUE TITLE
Bug: extra "Loading…" indicators

### ISSUE THREAD

**Issue by chrisgrieser** [Wansmer/symbol-usage.nvim#24] opened 2023-10-27 11:19 UTC
I am not 100% sure how to reproduce this, but I think one way to reproduce this are undos/redos where a function name or function existence is modified.

<img width="862" alt="Pasted image 2023-10-27 at 13 16 15@2x" src="https://github.com/Wansmer/symbol-usage.nvim/assets/73286100/ae0f8e7f-0543-4353-a40c-46e615b2630e">

**Comment by Wansmer** [comment] 2023-10-29 01:11
Unfortunately, I am not able to reproduce the bug using undo/redo.
If you're able to reproduce it again, please post the action steps, Neovim version, plugin setup and piece of code.

**Comment by chrisgrieser** [comment] 2023-12-26 18:01
So, the problem still occurs regularly, I *think* it's a combination of a function name being modified with high CPU usage, but that's just a guess, since I cannot reproduce really.

However, I was thinking, one simple way to kinda workaround this issue could be to allow for customization of the loading-text. In that case one could set the loading-text to an empty string 🙈

**Comment by Wansmer** [comment] 2023-12-26 18:06
> However, I was thinking, one simple way to kinda workaround this issue could be to allow for customization of the loading-text. In that case one could set the loading-text to an empty string 🙈

You can already do this with `request_pending_text = ''`.

I will try to investigate the issue with this problem in more detail.

**Comment by Green0wl** [comment] 2024-03-10 12:44
This happens almost every time I create a new function in `typescript` in conjunction with `Angular`.

**Comment by mortymacs** [comment] 2024-05-08 12:38
I have similar issue in Golang.

**Comment by Wansmer** [comment] 2024-05-08 12:42
> I have similar issue in Golang.

@mortymacs, please describe the steps to reproduce the bug.

**Comment by Wansmer** [comment] 2024-05-08 17:58
Ok, I was able to replicate the bug with `gopls` and after #56 it should work.
But most likely it's not the same bug as in the original issue, because the problem was in code that was added later than the creation of this issue.
@chrisgrieser, is the original issue still there after #56? (I still can't reproduce it).

**Comment by chrisgrieser** [comment] 2024-05-09 17:29
At least on my end, the issue does not occur anymore. Maybe some other commit in the meantime has fixed the issue?

**Comment by Wansmer** [comment] 2024-05-09 17:35
Thanks for the info. 

> Maybe some other commit in the meantime has fixed the issue?

Yeah, maybe. 
Then I'll close this is issue if the problem no longer occured.

**Closed by Wansmer** 2024-05-09 17:35 UTC
Labels: bug
